In [238]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense

In [239]:
data=pd.read_csv('mushrooms.csv')

In [240]:
data.head()

class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [241]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [242]:
data.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8124       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

In [243]:
from sklearn.preprocessing import LabelEncoder

In [244]:
le=LabelEncoder()

In [245]:
df=data.apply(func=le.fit_transform)

In [246]:
df.head()

class  cap-shape  cap-surface  ...  spore-print-color  population  habitat
0      1          5            2  ...                  2           3        5
1      0          5            2  ...                  3           2        1
2      0          0            2  ...                  3           2        3
3      1          5            3  ...                  2           3        5
4      0          5            2  ...                  3           0        1

[5 rows x 23 columns]

In [247]:
y=df['class']
X=df.drop(labels=['class'],axis=1)
df.shape

(8124, 23)

In [248]:
X.head()
X.shape[0],y.shape

(8124, (8124,))

In [249]:
from sklearn.model_selection import train_test_split

In [250]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [251]:
model=Sequential()

In [252]:
model.add(Dense(10,activation='sigmoid',input_dim=X.shape[1]))

In [253]:
model.add(Dense(5,activation='sigmoid'))

In [254]:
model.add(Dense(1,activation='sigmoid'))

In [259]:
model.compile(loss='mse',optimizer='adam',metrics=['accuracy'])

In [260]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 10)                230       
                                                                 
 dense_19 (Dense)            (None, 5)                 55        
                                                                 
 dense_20 (Dense)            (None, 1)                 6         
                                                                 
Total params: 291
Trainable params: 291
Non-trainable params: 0
_________________________________________________________________


In [261]:
model.fit(X_train,y_train,epochs=300,batch_size=1000,verbose=1)

Epoch 1/300
6/6 [==============================] - 1s 5ms/step - loss: 0.0520 - accuracy: 0.9434
Epoch 2/300
6/6 [==============================] - 0s 5ms/step - loss: 0.0517 - accuracy: 0.9438
Epoch 3/300
6/6 [==============================] - 0s 5ms/step - loss: 0.0514 - accuracy: 0.9438
Epoch 4/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0511 - accuracy: 0.9440
Epoch 5/300
6/6 [==============================] - 0s 5ms/step - loss: 0.0508 - accuracy: 0.9438
Epoch 6/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0505 - accuracy: 0.9438
Epoch 7/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0502 - accuracy: 0.9436
Epoch 8/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0499 - accuracy: 0.9438
Epoch 9/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0497 - accuracy: 0.9438
Epoch 10/300
6/6 [==============================] - 0s 4ms/step - loss: 0.0494 - accuracy: 0.9436
Epoch 11/300
6/6 [===========

In [262]:
y_pred=model.predict(X_test)

In [263]:
y_pred=(y_pred.round())
y_pred=y_pred.astype(int)

In [264]:
print(y_pred.shape)
y_pred=y_pred.reshape(2681,)
y_pred[:10]

(2681, 1)


array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [265]:
print(y_test.shape)
y_test[:10]

(2681,)


1971    0
6654    1
5606    1
3332    0
6988    1
5761    1
5798    1
3064    1
1811    0
3422    0
Name: class, dtype: int64

In [266]:
test_accuracy=sum(y_pred == y_test)/len(y_pred)

In [267]:
test_accuracy*100

99.1048116374487

In [268]:

y_pred1=model.predict(X_train)
y_pred1=y_pred1.round().astype(int)
y_pred1=y_pred1.reshape(y_train.shape[0],)
y_pred1

array([0, 1, 0, ..., 0, 1, 0])

In [269]:
y_pred1[:10]

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0])

In [270]:
y_train[:10]

3244    0
3739    1
2154    0
1344    0
7852    1
6104    1
4829    1
952     0
6964    1
1504    0
Name: class, dtype: int64

In [271]:
train_accuracy=sum(y_pred1 == y_train)/len(y_pred1)

In [272]:
train_accuracy*100

99.26511115193827

In [273]:
from sklearn.linear_model import LogisticRegression

In [274]:
m=LogisticRegression()

In [ ]:
m.fit(X_train,y_train)

In [276]:
y_pred2=m.predict(X_test)

In [277]:
y_test[:10]

1971    0
6654    1
5606    1
3332    0
6988    1
5761    1
5798    1
3064    1
1811    0
3422    0
Name: class, dtype: int64

In [279]:
y_pred2[:10]

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [278]:
m.score(X_test,y_test)

0.9474076837001119